apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-adapter.fullname" . }}
  labels:
    {{- include "service-adapter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "service-adapter.selectorLabels" . | nindent 4 }}
